version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "01:00"
      timezone: "UTC"
    # Group minor and patch updates together
    groups:
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Open PRs for major version updates
    open-pull-requests-limit: 10
    reviewers:
      - "kapilduraphe"
    assignees:
      - "kapilduraphe"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Rebase on conflicts
    rebase-strategy: "auto"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - "kapilduraphe"
    assignees:
      - "kapilduraphe"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    rebase-strategy: "auto"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "kapilduraphe"
    assignees:
      - "kapilduraphe"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "automated"
    rebase-strategy: "auto"
