name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run type-check

    - name: Build
      run: npm run build

    - name: Test build
      run: node dist/main.js --version

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v5

    - name: Build Docker image
      run: docker build -t mcp-watch .

    - name: Test Docker image
      run: |
        docker run --rm mcp-watch --version
        docker run --rm mcp-watch scan --help
